[project]
name = "PythonSortingAlgorithms"
version = "0.1.0"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "E225", "E226", "E227", "E228"]
preview = true

[tool.ruff.format]
indent-style = "space"
skip-magic-trailing-comma = false

